site_name: 'Deep Earthquake Catalog'
site_url: 'https://ai4eps.github.io/Earthquake-Deep-Catalog'
site_description: 'Deep-learning-based Earthquake Catalogs'
site_author: 'Weiqiang Zhu'
docs_dir: docs/
repo_name: 'Earthquake-Deep-Catalog'
repo_url: 'https://github.com/ai4eps/Earthquake-Deep-Catalog'
nav:
  - Overview: README.md
  - Hawaii: catalogs/Hawaii/info.md
    # - Full: catalogs/Hawaii/info.md
    # - Demo: catalogs/Hawaii/demo/info.md
  - Tonga: catalogs/Tonga/info.md

theme:
  name: 'material'
  features:
    - navigation.expand

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True

  # - redirects:
  #     redirect_maps:
  #       'earthquake-deep-catalog.md': 'https://ai4eps.github.io/Earthquake-Deep-Catalog/'
  #       'earthquake-catalog.md': 'https://ai4eps.github.io/Earthquake-Deep-Catalog/'
  #       'earthquakecatalog.md': 'https://ai4eps.github.io/Earthquake-Deep-Catalog/'
  #       'catalog.md': 'https://ai4eps.github.io/Earthquake-Deep-Catalog/'

# extra:
#   analytics:
#     provider: google
#     property: G-69DX3B35RK
